#!/bin/bash

# This shell script was written on Ubuntu 18.04 LTS for WSL
# This script will build a tree for each alignment file in `alignments/` 
# and output the '.treefile' with the same name as alignment into 'iqtree/'.
# Please make sure all files in `alignments/` are alignments generated by '4_alignment_blocks.sh'.

for file in $(ls alignments/*.phy)
do
    # Extract the basename
    filename=$(basename $file | sed 's/.phy//g') 
    # Build the tree:
    #   '-T AUTO': To automatically choose the number of threads appropriate for your machine;
    #   '-pre': Use the basename as prefix for outputs (in the main directory);
    #   '--no-log --no-iqtree -djc': To suppress the creation of the '.log', '.iqtree', '.bionj', and '.mldist' files;
    #   '-quiet': To run quietly without printing information to the screen);
    iqtree -s $file -m HKY+G -T AUTO -pre $filename --no-log --no-iqtree -djc -quiet
    # Move the output '.treefile' from main directory to 'iqtree/'
    mv $filename.treefile iqtree/$filename.treefile
    # Remove other output files in main directory
    rm $filename.*
done